### PR TITLE
Fix kubeflow link error

### PR DESCRIPTION
**Pull request by pingsutw**
Fix kubeflow link error

### CODE REVIEW

**Comment by tgaddair** [comment]
Hey @pingsutw, thanks for the PR!  

Just a couple things before we land. Could you sign the [DCO](https://github.com/horovod/horovod/pull/1585/checks?check_run_id=348645888).  Also, please update [index.rst](https://github.com/horovod/horovod/blob/master/docs/index.rst) to pass the Docs Summary Sync check.

**Comment by pingsutw** [comment]
Thanks @tgaddair for the review. 
1. update index.rst
2. update summary.rst 
3. sign the DCO.

**Comment by pingsutw** [comment]
The test fail seems unrelated

**Comment by tgaddair** [comment]
Thanks for following up @pingsutw.  Once #1587 lands we can rerun the tests.  When they pass, I'll go ahead and land this.

**Comment by pingsutw** [comment]
Got it, thanks for the help

**Comment by tgaddair** [comment]
@pingsutw, #1587 has landed.  Please rebase your branch on master then push again.  Unit tests should now succeed.

**Comment by pingsutw** [comment]
rebase it. Thanks to @tgaddair

**Pull request merged**
