### PR TITLE
Avoid overwriting methods in the super class of DBFSLocalStore

### PR DESCRIPTION
**Pull request by liangz1**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs?
- [ ] Did you write any tests to validate this change?
- [x] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

The issue is that on Databricks, DBFSLocalStore cannot correctly write intermediate files due to the previous PR #2376. I updated DBFSLocalStore to avoid overwriting the methods in the superclass: `matches` and `get_localized_path`, because those are needed for the underlying LocalStore to work correctly. The dbfs parsing logic should be defined in dedicated methods.

I manually tested the change on Databricks and it works well.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Review by tgaddair — APPROVED** [review]
LGTM!  @liangz1, can you sign the DCO for this commit?  Also, we will need to rerun tests once #2530 lands.

**Comment by liangz1** [comment]
The buildkite tests fail to build with torchvision errors, seems #2531 is fixing it.

@tgaddair Could you suggest the estimate:
1. When will the next maintenance version including this patch be released?
2. When will the horovod version supporting TF 2.4 with CUDA 11, and PyTorch 1.7.1 released?

Thanks!

**Comment by tgaddair** [comment]
> The buildkite tests fail to build with torchvision errors, seems #2531 is fixing it.
> 
> @tgaddair Could you suggest the estimate:
> 
> 1. When will the next maintenance version including this patch be released?
> 2. When will the horovod version supporting TF 2.4 with CUDA 11, and PyTorch 1.7.1 released?
> 
> Thanks!

Hey @liangz1,

I'd like to release v0.21.1 early next week once this PR and a few others are landed.

Horovod is already compatible with TF 2.4, CUDA 11, and PyTorch 1.7.1 to my knowledge.  Have you experienced issues with any of these versions?

**Comment by liangz1** [comment]
Thanks for sharing the info! I just want to confirm the supported version before upgrading.

**Comment by liangz1** [comment]
@tgaddair There seems to be an error with the unit test report generation. Can you double-check and suggest whether this PR is ready for merging?

**Review by tgaddair — APPROVED** [review]
LGTM!  There was an update to the workflow code after this PR was created, so I suspect that was the issue.

**Pull request merged**
