### PR TITLE
[ROCm] upate for new hipify logic for PyTorch builds

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes building Horovod for ROCm PyTorch that uses newer behavior for the hipify script.

### CODE REVIEW

**Comment by jeffdaily** [comment]
CC @jithunnair-amd, preparing for https://github.com/pytorch/pytorch/pull/45451.

**Comment by jithunnair-amd** [comment]
@jeffdaily This needs some love :)

**Comment by jeffdaily** [comment]
@tgaddair now that https://github.com/pytorch/pytorch/pull/45451 has merged (really https://github.com/pytorch/pytorch/pull/48715), could you review or delegate the review for this PR?   Thanks.

**Comment by tgaddair** [comment]
Sounds good @jeffdaily, thanks!

**Review by tgaddair — APPROVED** [review]
LGTM!  Let's land once tests pass.

**Pull request merged**
