### PR TITLE
Estimator: prefetch next batch for keras dataset

### PR DESCRIPTION
**Pull request by chongxiaoc**
From https://www.tensorflow.org/guide/data_performance#prefetching, this
is suggested for training speed improvement.

Signed-off-by: Chongxiao Cao <chongxiaoc@uber.com>

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by chongxiaoc** [comment]
Training tests on Uber side shows the improvement.

5+M rows Training on 6 GPUs

**Comment by chongxiaoc** [comment]
@tgaddair Can you have a check for this?

**Comment by chongxiaoc** [comment]
Synced with @tgaddair , to rerun with `tf.data.AUTOTUNE` for buffer size.

**Comment by chongxiaoc** [comment]
Updated with `tf.data.AUTOTUNE` (for tensorflow2+)

**Review by tgaddair — APPROVED** [review]

**Pull request merged**
