### PR TITLE
[Spark]: expose random seed as an optional parameter

### PR DESCRIPTION
**Pull request by chongxiaoc**
For model training reproducibility.

Signed-off-by: Chongxiao Cao <chongxiaoc@uber.com>

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [x] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Review by Tixxx — APPROVED** [review]

**Review by EnricoMi — APPROVED** [review]
LGTM! except for the failing tests.

**Comment by chongxiaoc** [comment]
I think I didn't realize TF1 and TF2 have different function name for setting random seed.

**Comment by chongxiaoc** [comment]
It looks like we got some git repo checkout issues in our CI.

```
  Error: fatal: unable to access 'https://github.com/boostorg/static_assert.git/': The requested URL returned error: 429
  Error: fatal: clone of 'https://github.com/boostorg/static_assert.git' into submodule path '/Users/runner/work/horovod/horovod/third_party/boost/static_assert' failed
```

**Comment by EnricoMi** [comment]
> It looks like we got some git repo checkout issues in our macOS CI.

Rerunning those failed jobs only solved it.

**Pull request merged**
