### PR TITLE
Fix RelWithDebInfo build, make it the default with -03 optimizations

### PR DESCRIPTION
**Pull request by leezu**
As per discussion in https://github.com/horovod/horovod/pull/2263

Thanks @nvcastet

### CODE REVIEW

**Comment by tgaddair** [comment]
Very strange, looks like Horovod builds successfully but fails at runtime with this setting.

**Comment by leezu** [comment]
Previously we had `-pthread -fPIC -O3 -Wall -ftree-vectorize -g` now we have `-pthread -fPIC -Wall -ftree-vectorize -g -O3`. I'm not sure why there is any effect on the runtime.

**Comment by tgaddair** [comment]
Hey @leezu, based on this change, is your conclusion that we're best off reverting #2263?

**Comment by nvcastet** [comment]
@leezu @tgaddair ok I think i fixed it. RelWithDebInfo was missing from the Utilities cmake script. I also use -03 in RelWithDebInfo because RelWithDebInfo uses -02 by default, and i remove our logic around cmake build type because cmake adds the good flags by default.

**Review by leezu — COMMENTED** [review]
Thank you @nvcastet

**Review by tgaddair — APPROVED** [review]
Thanks @nvcastet!  Can confirm this works on macOS as well.

**Pull request merged**
