### PR TITLE
Fix ignored cuda arch flags

### LINKED ISSUE #3460: pytorch model weights aren't updated properly in `horovod/horovod:0.24.1` docker image
**Environment:**
1. Framework: PyTorch
3. Horovod version: "official" docker images for 0.24.0 and 0.24.1
13. Host: ubuntu 18.04, Docker 20.10.12, nvidia drivers 470.103.01, 8 x Tesla K80

**Bug report:**
In the recent "official" `horovod/horovod:0.24.1` docker image, model weights doesn't seem to be updated properly between iterations. 

Test script:
```
from typing import Any, Dict, Tuple

import torch.utils.data
import horovod.torch as hvd

hvd.init()
torch.cuda.set_device(hvd.local_rank())

class OnesDataset(torch.utils.data.Dataset):
    def __len__(self) -> int:
        return 64

    def __getitem__(self, index: int) -> Tuple:
        return torch.Tensor([float(1)])

train_dataset = OnesDataset()

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=16)

model = torch.nn.Linear(1, 1, False)
model.weight.data.fill_(0)
model = model.cuda()

loss_fn = torch.nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), 0.1)
optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())

hvd.broadcast_parameters(model.state_dict(), root_rank=0)

for epoch in range(1):
    for batch_idx, data in enumerate(train_loader):
        data = data.cuda()
        optimizer.zero_grad()
        output = model(data)
        loss = loss_fn(output, data)
        loss.backward()
        optimizer.step()
        if hvd.rank() == 0:
            weight = model.weight.data.item()
            print('weight:', weight)
```

Running `horovodrun -np 2 python train.py` in `horovod/horovod:0.24.1` or `horovod/horovod:0.24.0` outputs: ```
[1,0]<stdout>:weight: 0.20000000298023224                                                                                
[1,0]<stdout>:weight: 0.20000000298023224                                                                                
[1,0]<stdout>:weight: 0.20000000298023224                                                                                
[1,0]<stdout>:weight: 0.20000000298023224      
```

Notice that the weights are the same — they aren't updated.

**Expected behavior:**
Running the same in our own (Determined AI's) docker images with (pytorch 1.9 + cuda 11.1) or (pytorch 1.10.2 + cuda 11.3) and the same horovod versions (these are based on corresponding `nvidia/cuda` images, e.g. `determinedai/environments-dev:cuda-11.3-pytorch-1.10-lightning-1.5-tf-2.8-gpu-3da66d1`) works okay: ```
[0]<stdout>:weight: 0.20000000298023224
[0]<stdout>:weight: 0.36000001430511475
[0]<stdout>:weight: 0.4880000054836273
[0]<stdout>:weight: 0.590399980545044
```

 I suspect something is wrong with the official docker build.

### PR DESCRIPTION
**Pull request by nvcastet**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [x] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

The cuda architecture flags were ignored during our build:
```
# cuobjdump -lelf mpi_lib_v2.cpython-38-x86_64-linux-gnu.so
ELF file    1: mpi_lib_v2.cpython-38-x86_64-linux-gnu.1.sm_52.cubin
ELF file    2: mpi_lib_v2.cpython-38-x86_64-linux-gnu.2.sm_35.cubin
ELF file    3: mpi_lib_v2.cpython-38-x86_64-linux-gnu.3.sm_50.cubin
ELF file    4: mpi_lib_v2.cpython-38-x86_64-linux-gnu.4.sm_60.cubin
ELF file    5: mpi_lib_v2.cpython-38-x86_64-linux-gnu.5.sm_61.cubin
ELF file    6: mpi_lib_v2.cpython-38-x86_64-linux-gnu.6.sm_70.cubin
ELF file    7: mpi_lib_v2.cpython-38-x86_64-linux-gnu.7.sm_80.cubin
```
Looking at the build output, nvcc was building the cuda object files with the good architecture flags but was doing device linking as a separate step (CUDA_SEPARABLE_COMPILATION) without any architecture flags.
We could add the flags to the extra device linking step but there is no reason to have a separated device linking step since all our device function calls are in the same compilation unit.
Therefore, this PR removes the `CUDA_SEPARABLE_COMPILATION` cmake setting so that we compile/dlink in one step with the good flags.

```
# cuobjdump -lelf mpi_lib_v2.cpython-38-x86_64-linux-gnu.so
ELF file    1: mpi_lib_v2.cpython-38-x86_64-linux-gnu.1.sm_35.cubin
ELF file    2: mpi_lib_v2.cpython-38-x86_64-linux-gnu.2.sm_50.cubin
ELF file    3: mpi_lib_v2.cpython-38-x86_64-linux-gnu.3.sm_60.cubin
ELF file    4: mpi_lib_v2.cpython-38-x86_64-linux-gnu.4.sm_61.cubin
ELF file    5: mpi_lib_v2.cpython-38-x86_64-linux-gnu.5.sm_70.cubin
ELF file    6: mpi_lib_v2.cpython-38-x86_64-linux-gnu.6.sm_80.cubin
ELF file    7: mpi_lib_v2.cpython-38-x86_64-linux-gnu.7.sm_35.cubin
ELF file    8: mpi_lib_v2.cpython-38-x86_64-linux-gnu.8.sm_37.cubin
ELF file    9: mpi_lib_v2.cpython-38-x86_64-linux-gnu.9.sm_50.cubin
ELF file   10: mpi_lib_v2.cpython-38-x86_64-linux-gnu.10.sm_52.cubin
ELF file   11: mpi_lib_v2.cpython-38-x86_64-linux-gnu.11.sm_53.cubin
ELF file   12: mpi_lib_v2.cpython-38-x86_64-linux-gnu.12.sm_60.cubin
ELF file   13: mpi_lib_v2.cpython-38-x86_64-linux-gnu.13.sm_61.cubin
ELF file   14: mpi_lib_v2.cpython-38-x86_64-linux-gnu.14.sm_62.cubin
ELF file   15: mpi_lib_v2.cpython-38-x86_64-linux-gnu.15.sm_70.cubin
ELF file   16: mpi_lib_v2.cpython-38-x86_64-linux-gnu.16.sm_72.cubin
ELF file   17: mpi_lib_v2.cpython-38-x86_64-linux-gnu.17.sm_75.cubin
ELF file   18: mpi_lib_v2.cpython-38-x86_64-linux-gnu.18.sm_80.cubin
ELF file   19: mpi_lib_v2.cpython-38-x86_64-linux-gnu.19.sm_86.cubin
```

Fixes #3460 #3461 
## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by ioga** [comment]
Can confirm this fixes #3461 👍 
Can't tell on #3460 cause that'd need an "official" docker build.

**Review by maxhgerlach — APPROVED** [review]
Great catch, thanks for the quick fix @nvcastet!

I cannot tell anymore what prompted me to put `CUDA_SEPARABLE_COMPILATION ON` there. Probably a remnant from triaging some other build error.

**Comment by maxhgerlach** [comment]
I retriggered the CI jobs because in the original run one of the macOS builds was stuck somehow (couldn't see logs of course).

> @nvcastet @maxhgerlach would you say we need a hotfix v0.24.2 release?

This appears to break Horovod in popular cloud environments, so releasing the fix quickly sounds like a very good idea to me.

**Comment by nvcastet** [comment]
> @nvcastet @maxhgerlach would you say we need a hotfix v0.24.2 release?
@EnricoMi yes for new release but needs to decide if we cherry pick to hotfix branch or not.

**Pull request merged**
