### PR TITLE
Fixed global_step assign_add ordering during TF gradient aggregation

### LINKED ISSUE #2715: Bug in global_step update when local gradient aggregation is used
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.15.3
3. Horovod version: 0.21.3
4. MPI version: 3.1.6
5. CUDA version: 11.0.194
6. NCCL version: 2.7.6
7. Python version: 3.6.9
8. Spark / PySpark version:
9. OS and version: 
10. GCC version:
11. CMake version:

**Bug report:**
There seems to be a bug in how the `global_step` variable is updated when using local gradient aggregation with `backward_passes_per_step>1`. 

Here is a simple example to reproduce the issue:
```
import tensorflow as tf
import horovod.tensorflow as hvd

tf.disable_eager_execution()
LR=0.01
# data/label is always just 1
data = tf.constant([[1]], dtype=tf.float32)
# one-variable linear model, no bias (y = w*x)
#
# gradient update is hand-calculatable if needed for testing:
#
# model:            yhat = w*x
# mse loss:         L = (ytrue - w*x)**2
# gradient:         dL/dw = -2*x*(ytrue - `w*x)`
# let ytrue = x:    dL/dw = -2*x*x*(1-w)
def predict(x):
    dense = tf.layers.Dense(1, use_bias=False, kernel_initializer=tf.zeros_initializer())
    return dense(x)
pred = predict(data)
loss = tf.losses.mean_squared_error(data, pred)
step = tf.contrib.framework.get_or_create_global_step()
optimizer = tf.train.GradientDescentOptimizer(LR)
hvd.init()
optimizer = hvd.DistributedOptimizer(optimizer, backward_passes_per_step=2, average_aggregated_gradients=True)

with tf.control_dependencies([tf.print("step:", step, "loss:", loss)]):
    train_op = optimizer.minimize(loss, global_step=step)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    # training loop
    for i in range(10):
        sess.run([train_op])
```

Which gives this output:
```
step: 0 loss: 1
step: 0 loss: 1
step: 0 loss: 1
step: 2 loss: 0.960400045
step: 2 loss: 0.960400045
step: 4 loss: 0.922368109
step: 4 loss: 0.922368109
step: 6 loss: 0.885842443
step: 6 loss: 0.885842443
step: 8 loss: 0.850763
step: 8 loss: 0.850763
```

### PR DESCRIPTION
**Pull request by rb-determined-ai**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? *no docs change to make*
- [x] Did you write any tests to validate this change?
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users? *not yet*

## Description

Fixed global_step assign_add ordering during TF gradient aggregation.  Includes a test which fails without the fix.

Fixes #2715 (issue).

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
cc @chongxiaoc

Right now the PR just includes a unit test that will hopefully fail without the fix (I don't have a way to test locally).

**Comment by rb-determined-ai** [comment]
All right, [this](https://github.com/horovod/horovod/runs/2144558231) is the failure I was looking for:

```
            for idx in range(10):
                step, _ = sess.run((global_step_before_update, update_op))
                computed_value = sess.run(opt._optimizer.variable.read_value())[0]
>               assert step == max(idx - 1, 0)
E               AssertionError: assert 1 == 0
E                 +1
E                 -0
```

**Review by tgaddair — APPROVED** [review]
LGTM! Thanks for the fix.

@chongxiaoc can you also review?

**Comment by chongxiaoc** [comment]
@tgaddair 
I'm waiting for the diff from #2715 to fix the failure.
Right now it only has unit test commit.

I checked and  tested the diff in  #2715, it was working for the issue repro.

**Comment by rb-determined-ai** [comment]
Yeah, I couldn't tell quite how I failed the test from before, so I rewrote the test and I'm in the process of rerunning the test.

It's a little slow since I can't run the test locally, but it's coming.

**Comment by rb-determined-ai** [comment]
Alright!  @ioga helped me fix the unit test.  The issue was with the unit test; the fix looks to be correct.  @chongxiaoc, please take a look.

**Comment by chongxiaoc** [comment]
Are there still some errors in buildkite?

**Review by chongxiaoc — APPROVED** [review]
LGTM

**Comment by chongxiaoc** [comment]
@tgaddair Can we merge this PR?

**Pull request merged**
