### PR TITLE
Add missing import for torch.nn.functional

### PR DESCRIPTION
**Pull request by terrytangyuan**
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by alsrgv** [comment]
I think it'd be better to just add import `import torch.nn.functional as F`.

**Comment by alsrgv** [comment]
@terrytangyuan, thanks!  Can you fix the DCO?

**Comment by terrytangyuan** [comment]
@alsrgv Fixed. Do you know if there's a way to automatically do this on the Github UI for simple changes like these (had to do this locally with git)?

**Comment by alsrgv** [comment]
@terrytangyuan, no :-(  I didn't look hard though.  Thanks for the PR!

**Pull request merged**
