### PR TITLE
Install horovod for all frameworks in Dockerfile, incl. Spark

### PR DESCRIPTION
**Pull request by EnricoMi**
Installing horovod does not install all dependencies. Also installs pyspark and Spark.

What is the purpose of these docker images? Are those pushed to docker hub? What do you think of adding spark to them?

### CODE REVIEW

**Comment by tgaddair** [comment]
Good idea @EnricoMi.  The goal of these images should be to run Horovod in your chosen environment without needing to figure out which packages you need.  So adding Spark, Ray, etc. sounds like a good idea to me.

**Review by tgaddair — APPROVED** [review]
I like this approach, could also add Ray in the future, maybe as different Dockerfiles for Spark and Ray.

**Comment by EnricoMi** [comment]
> could also add Ray in the future

Maybe ray should be added to `all-frameworks`.

**Comment by tgaddair** [comment]
I think it is, but there are some dependencies that are needed to make it work in Docker. I have them locally, but will make a note to add them to the examples.

**Pull request merged**
