### PR TITLE
fix issue 3264

### LINKED ISSUE #3264: All workers failed on failure with Elastic Horovod
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): PyTorch
2. Framework version: 1.10
3. Horovod version: latest master (3efc229a8d12c250ea4a3493dc01aa8241a10899)
4. MPI version: 
5. CUDA version: 10.2
6. NCCL version: 2.7.6
7. Python version: 3.6
8. Spark / PySpark version:
9. Ray version:
10. OS and version: ubuntu 18.04lts
11. GCC version: 7.5
12. CMake version: 3.21.3

**Bug report:**

We found that this PR https://github.com/horovod/horovod/pull/3112 solved the some problems of NCCL. So we tested it with the latest code. However, we found sometimes all workers failed on failure. 

We have two machines, each equipped with 2 P100 GPUs. We run the program in the master node (10.28.1.16) with the following command:
```sh
horovodrun -np 4 --min-np 2 -H 10.28.1.16:2,10.28.1.17:2 --start-timeout 600 python pytorch_synthetic_benchmark_elastic.py
```

During the execution, we **intentionally killed** the workers on the host (10.28.1.17) with `pkill python`. The workers on that host died immediatelly. 

However, sometimes the workers in the master host also failed and exited with the status code 134. From the log, it seems that the workers did not re-initialize since the `initialization_done` is `false`. This is weird because the alive workers should re-init (https://github.com/horovod/horovod/blob/master/horovod/torch/elastic/__init__.py#L48). 
```sh
(d2l) ➜  pytorch git:(master) ✗ horovodrun -np 4 --min-np 2 --host-discovery-script ./discover_hosts.sh --start-timeout 600 --network-interface eth2 python pytorch_synthetic_benchmark_elastic.py
[0]<stdout>:Model: resnet50
[0]<stdout>:Batch size: 32
[0]<stdout>:Number of GPUs: 4
[0]<stdout>:Running warmup...
[0]<stdout>:Running benchmark...
[0]<stdout>:Iter #0: 48.1 img/sec per GPU
[0]<stderr>:[2021-11-08 15:08:30.430065: E /home/gmsheng/horovod/horovod/common/operations.cc:654] [0]: Horovod background loop uncaught exception: [/opt/conda/conda-bld/pytorch_1634272115665/work/third_party/glo
o/gloo/transport/tcp/pair.cc:598] Connection closed by peer [10.28.1.17]:52145
[1]<stderr>:[2021-11-08 15:08:30.430133: E /home/gmsheng/horovod/horovod/common/operations.cc:654] [1]: Horovod background loop uncaught exception: [/opt/conda/conda-bld/pytorch_1634272115665/work/third_party/glo
o/gloo/transport/tcp/pair.cc:598] Connection closed by peer [10.28.1.17]:49285
Process 2 exit with status code 255.
Process 3 exit with status code 255.
[0]<stderr>:python: /home/gmsheng/horovod/horovod/common/process_set.cc:20: bool horovod::common::ProcessSet::IsCurrentProcessIncluded() const: Assertion `initialization_done' failed.
[1]<stderr>:python: /home/gmsheng/horovod/horovod/common/process_set.cc:20: bool horovod::common::ProcessSet::IsCurrentProcessIncluded() const: Assertion `initialization_done' failed.
[1]<stderr>:Aborted (core dumped)
Process 1 exit with status code 134.
[0]<stderr>:Aborted (core dumped)
Process 0 exit with status code 134.
ERROR:root:failure count == 4 -> stop running
Traceback (most recent call last):
  File "/home/gmsheng/.conda/envs/d2l/bin/horovodrun", line 33, in <module>
    sys.exit(load_entry_point('horovod', 'console_scripts', 'horovodrun')())
  File "/home/gmsheng/horovod/horovod/runner/launch.py", line 770, in run_commandline
    _run(args)
  File "/home/gmsheng/horovod/horovod/runner/launch.py", line 758, in _run
    return _run_elastic(args)
  File "/home/gmsheng/horovod/horovod/runner/launch.py", line 668, in _run_elastic
    gloo_run_elastic(settings, env, args.command)
  File "/home/gmsheng/horovod/horovod/runner/gloo_run.py", line 350, in gloo_run_elastic
    launch_gloo_elastic(command, exec_command, settings, env, get_common_interfaces, rendezvous)
  File "/home/gmsheng/horovod/horovod/runner/gloo_run.py", line 337, in launch_gloo_elastic
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 10.28.1.17[0]
Exit code: 255
```

**Expected behaviour**:

The program continues to execute normally in the master host. Sometimes we found it succeed as shown in the log below. 
```sh
(d2l) ➜  pytorch git:(master) ✗ horovodrun -np 4 --min-np 2 --host-discovery-script ./discover_hosts.sh --start-timeout 600 --network-interface eth2 python pytorch_synthetic_benchmark_elastic.py                 [
0]<stdout>:Model: resnet50
[0]<stdout>:Batch size: 32
[0]<stdout>:Number of GPUs: 4
[0]<stdout>:Running warmup...
[0]<stdout>:Running benchmark...
[0]<stdout>:Iter #0: 52.9 img/sec per GPU
[0]<stdout>:Iter #1: 30.3 img/sec per GPU
[0]<stderr>:[2021-11-08 13:56:12. 47430: E /home/gmsheng/horovod/horovod/common/operations.cc:654] [0]: Horovod background loop uncaught exception: [/opt/conda/conda-bld/pytorch_1634272115665/work/third_party/glo
o/gloo/transport/tcp/pair.cc:589] Read error [10.28.1.17]:58789: Connection reset by peer
[1]<stderr>:[2021-11-08 13:56:12.115609: E /home/gmsheng/horovod/horovod/common/operations.cc:654] [1]: Horovod background loop uncaught exception: [/opt/conda/conda-bld/pytorch_1634272115665/work/third_party/glo
o/gloo/transport/tcp/pair.cc:598] Connection closed by peer [10.28.1.17]:26242
Process 3 exit with status code 255.
Process 2 exit with status code 255.
WARNING:root:blacklist failing host: 10.28.1.17
[0]<stdout>:Iter #1: 140.5 img/sec per GPU
[0]<stdout>:Iter #2: 142.1 img/sec per GPU
[0]<stdout>:Iter #3: 141.8 img/sec per GPU
[0]<stdout>:Iter #4: 139.9 img/sec per GPU
[0]<stdout>:Iter #5: 138.3 img/sec per GPU
[0]<stdout>:Iter #6: 135.8 img/sec per GPU
[0]<stdout>:Iter #7: 139.1 img/sec per GPU
[0]<stdout>:Iter #8: 139.2 img/sec per GPU
[0]<stdout>:Iter #9: 138.0 img/sec per GPU
[0]<stdout>:Img/sec per GPU: 121.6 +-74.6
[0]<stdout>:Total img/sec on 2 GPU(s): 243.3 +-149.2
```

**Other information:**

We build horovod from source. Here is our installation command. 
```sh
HOROVOD_DEBUG=1 CXX=/usr/bin/g++ CC=/usr/bin/gcc HOROVOD_WITHOUT_MPI=1 HOROVOD_WITH_GLOO=1  HOROVOD_NCCL_HOME=/usr/local/cuda HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITHOUT_MXNET=1 pip install --no-cache-dir -v -e .
```

```sh
~ horovodrun --check-build
Horovod v0.23.0:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [ ] MPI
    [X] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [ ] MPI
    [X] Gloo
```

___

cc: @woodlgz @tgaddair

### PR DESCRIPTION
**Pull request by woodlgz**
## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes #3264.
avoid enqueuing more collective ops while horovod is shutting down.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Review by tgaddair — COMMENTED** [review]
Thanks for the PR @woodlgz. Can you rebase off master to pick up any test fixes?

@romerojosh can you double check the changes to checking the shut down state here? It looks like it should be fine, but wanted to get a second opinion.

**Comment by romerojosh** [comment]
The changes look fine to me, but I'm not exactly sure what we expect to happen in an elastic scenario, which seems to be what this issue is about.

In an elastic case, do we expect these workers to resubmit these collective requests? If so, then this change looks good to me.

**Comment by ashahab** [comment]
@romerojosh I have a clarifying question: is `horovod_global.shut_down` a worker-only state or a shared state among all workers? If it's the former then yes, the remaining elastic workers should resubmit the collective ops(after forming a new ring).

**Comment by woodlgz** [comment]
@ashahab yes, horovod_global.shut_down is a  worker only state, but somehow all workers remaining will reach a common shutdown state and in elastic training they will form a new ring in next loop.
@romerojosh current training loop is wrapped in a so-called elastic loop in https://github.com/horovod/horovod/blob/master/horovod/common/elastic.py#L151. so in next loop,user training function will try to redo the calculation and resubmit the ops.

**Review by tgaddair — APPROVED** [review]
LGTM! Looks like the failing tests are head versions, which have some known issues being addressed. So we can go ahead and land this.

**Pull request merged**
