### PR TITLE
test: fix XOR model in test_spark_lightning.py

### PR DESCRIPTION
**Pull request by chongxiaoc**
Add missing return value of validation_step().

Signed-off-by: Chongxiao Cao <chongxiaoc@uber.com>

## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by EnricoMi** [comment]
@chongxiaoc I have merged latest master into your branch to trigger a new build. Workflow `CI (Results)` was broken, which I just fixed: #3565.

**Comment by EnricoMi** [comment]
Your non-head GPU tests are all green: https://buildkite.com/horovod/horovod/builds/7818

**Comment by chongxiaoc** [comment]
> Your non-head GPU tests are all green: https://buildkite.com/horovod/horovod/builds/7818

Thanks! I created an issue for failed unit test with TF head here: https://github.com/horovod/horovod/pull/3564#issuecomment-1146312804

**Review by Tixxx — APPROVED** [review]

**Comment by Tixxx** [comment]
LGTM

**Pull request merged**
