### PR TITLE
Update Dockerfile & tests to TF 1.14.0 + RDMA

### PR DESCRIPTION
**Pull request by alsrgv**
* Upgrade Dockerfile to TensorFlow 1.14.0 & CUDA 10
* Add Ubuntu 18.04 bundled RDMA drivers

### CODE REVIEW

**Comment by byronyi** [comment]
That's great. Congrats! Btw do you find a workaround to the hwloc issue? Your PR doesn't ship with 1.14, which is quite a pity.

**Comment by alsrgv** [comment]
@byronyi, can you try to `LD_PRELOAD=/path/to/system/libhwloc`?  That may help with symbol discovery.

**Comment by alsrgv** [comment]
I did not see any hwloc-related issues in the Dockerfiles or integration tests - maybe because they're using a more recent Open MPI 4.0.0.

**Comment by byronyi** [comment]
> @byronyi, can you try to `LD_PRELOAD=/path/to/system/libhwloc`? That may help with symbol discovery.

Yep, that works. Although we cherry-picked your PR with our in-house built TF :)

> I did not see any hwloc-related issues in the Dockerfiles or integration tests - maybe because they're using a more recent Open MPI 4.0.0.

I kinda expect that. Good for you!

**Pull request merged**
