### PR TITLE
Bump version to 0.24.0

### PR DESCRIPTION
**Pull request by EnricoMi**

### CODE REVIEW

**Review by alsrgv — APPROVED** [review]

**Review by nvcastet — APPROVED** [review]

**Review by tgaddair — APPROVED** [review]

**Review by chongxiaoc — APPROVED** [review]

**Comment by EnricoMi** [comment]
@maxhgerlach would like to have #3371 included, as this release moves to CMake 3.13+, which is not part of Ubuntu 18.04.

**Comment by EnricoMi** [comment]
This temporary install of CMake is tested in our CI: we have a few test images that run on Ubuntu 18.04 (where CMake is temporarily installed and work) and most run on Ubuntu 20.04 (which do not install and work well too).

**Comment by EnricoMi** [comment]
@tgaddair there is a huge backlog of commits in the CI, I'd wait for master commits to complete before merging this into master

**Review by maxhgerlach — APPROVED** [review]

**Comment by tgaddair** [comment]
Sounds good @EnricoMi.

**Pull request merged**
