### PR TITLE
Fixed spark keras "IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpn_eenlao/checkpoint'" error

### PR DESCRIPTION
**Pull request by kamalsharma2**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [x] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description
While using horovod v0.22.1 with tensorflow v2.4.2, a checkpoint error occurs during training. The error logs have been mentioned in #2988. This pr fixes the issue with loading the saved checkpoints for tensorflow version greater than 2.0.0

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Review by chongxiaoc — APPROVED** [review]

**Review by tgaddair — APPROVED** [review]

**Comment by kamalsharma2** [comment]
When is the next release of horovod planned in which these changes will be added?

**Comment by kamalsharma2** [comment]
@tgaddair

**Comment by chongxiaoc** [comment]
@kamalsharma2 I think it is blocked by https://github.com/horovod/horovod/issues/3149

**Comment by kamalsharma2** [comment]
@chongxiaoc I see that #3149 has been resolved by #3159. Can we expect a release anytime soon?

**Comment by chongxiaoc** [comment]
@kamalsharma2  We are working on removing final blockers for next release now.
#3149 is not fixed yet, we are still working on it.

**Comment by chongxiaoc** [comment]
two blocking PRs we are currently working on to cut the next release:
#3175  this is related to above torch nightly failure
#3157 this is related to the way of correctly import keras for tf>=2.5

FYI @kamalsharma2

**Pull request merged**
