### PR TITLE
Support backward_passes_per_step > 1 for TF Keras Eager Execution

### PR DESCRIPTION
**Pull request by aaron276h**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [x] Did you write any tests to validate this change?  
- [x] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description
This PR is a follow up #2346. This PR adds support for backward_passes_per_step > 1 for TF Keras optimizers executing in graph(non-eager) mode. This is one of the features that we have built into [Determined AI's](https://determined.ai/) fork of Horovod that we would like to upstream.

### CODE REVIEW

**Comment by aaron276h** [comment]
PR is currently failing: `test-cpu-gloo-py3_8-tf2_3_0-keras2_3_1-torch1_6_0-mxnet1_5_0-pyspark3_0_1` but doesn't seem related to the changes, likely a py3.8 issue.

**Comment by tgaddair** [comment]
Hey @aaron276h, landed a fix for the Python 3.8n issue, please rebase and force push.

**Comment by aaron276h** [comment]
Thanks @tgaddair!

**Review by tgaddair — APPROVED** [review]
LGTM!

**Pull request merged**
