### PR TITLE
Add GitHub Workflow CI

### PR DESCRIPTION
**Pull request by EnricoMi**
A GitHub Workflow for running the CPU test pipeline.
[grafik](https://github.com/horovod/horovod/actions/runs/1003273503)

CPU tests finish in 1:30 on GitHub, GPU tests finish in 1:15 on Buildkite.

The workflow file is generated by Python script `.github/gen-workflow-ci.py` based on the output of `.buildkite/gen-pipeline.sh`, so that we implement test logic only in one place.

These are the implemented features:
- builds all CPU images and runs appropriate tests
- builds GPU images but does not run any tests
- tests for GPU images are run on Buildkite after all above builds and tests succeed
- tests three images on macOS (replaces TravisCI)
- images where all frameworks are nightly versions do not prevent the Buildkite tests
- PRs without code changes (e.g. docs only) to not run the full build and test cycle (that is what Buildkite pipeline does)
- test results are downloaded from Buildkite and together with GitHub test results posted to the pull request
- build and test steps have timeouts and are [retried three times](https://github.com/horovod/horovod/runs/2255478598?check_suite_focus=true#step:15:910)
- workflow detects when its yaml file is not up-to-date
- earlier workflow runs on the same branch are cancelled
- triggering the Buildkite builds and publishing test results for fork PRs (can only be tested after merging to master)
- daily master build schedule
- Docker images are build on PR (not pushed), as well as master and version tags (and pushed to Dockerhub), but only if the build and test jobs succeed
- Docs and example sync workflows integrated into the CI workflow

Limitations:
- Buildkite build always has [author "Travis Addair" and build title "GPU Tests triggered by GitHub"](https://buildkite.com/horovod/horovod/builds/5298): we may use a service account here.
- ONECCL image does not build and is excluded (af2f3bbf): https://github.com/horovod/horovod/runs/2221724507?check_suite_focus=true (#2846)
- Workflow runs on one branch block other workflow runs, so that GitHub workflows can quickly saturate

Missing:
- disable Buildkite triggered by git pushs (with this merged into master the buildkite pipeline is empty)

### CODE REVIEW

**Comment by leezu** [comment]
> GitHub hosted workers have too limited disks to pull latest docker images and build horovod (especially GPU images) to benefit from docker caches for building: ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Do you know which docker build steps are the longest running ones? As docker cache is ruled out due to disk space limitation, some caching could still be achieved by relying on dockerfile v1.2 cache mount to mount smaller caches from the github actions runner into the container.

For example, if the docker build is slowed down by a compilation step, we can mount a ccache directory into the docker build process and use ccache to speed up the build: `RUN --mount=type=cache,target=/root/.ccache` instead of `RUN`, adding `#syntax=docker/dockerfile:1.2` as first line in the Dockerfile and ensuring docker buildkit is used instead of the legacy build.

**Comment by EnricoMi** [comment]
@leezu will build time benefit from docker buildkit caches even with cold caches or only when caches are populated after a similar run?

**Comment by leezu** [comment]
https://github.com/actions/cache can store the cache to a central location after each run. Every new run can initialize the cache from the most recent cache entry. When using https://ccache.dev/ to cache compilation steps, the time spent on compilation will be proportional to the number of changed compilation units (cache misses). (This example assumes that the docker build is currently slowed down by compiling c/c++ code and the cache would only help to speed up that particular compilation step.)

For example, the following snippet

```
      - name: Compilation cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          # We include the commit sha in the cache key, as new cache entries are
          # only created if there is no existing entry for the key yet.
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          # Restore any ccache cache entry, if none for
          # ${{ runner.os }}-ccache-${{ github.sha }} exists
          restore-keys: |
            ${{ runner.os }}-ccache

```

**Comment by EnricoMi** [comment]
Yes, the cache action, good point. Though, 5 GB is not much across all images. I'll have a quick look on which phase of building takes how long and I think buildkit should work on GitHub, so I would finally be able to get buildx working (#2618).

Maybe I move this improvement to another PR once this is merged into master.

**Comment by EnricoMi** [comment]
@leezu for some reason, the MXNet tests fail on macOS for one of the three setups that all succeed on TravisCI:

https://github.com/horovod/horovod/runs/2646968925?check_suite_focus=true

Could you have a look at the issue? I am puzzled.

**Comment by leezu** [comment]
@EnricoMi I think you're referring to the following error? Is the error persistent? As the error is related to gloo, should we try updating gloo first? `uv_read_start: connection already in progress` 

```
[1]<stdout>:============================= test session starts ==============================
[1]<stdout>:platform darwin -- Python 3.7.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/runner/.pyenv/versions/3.7.7/bin/python
[1]<stdout>:cachedir: .pytest_cache
[1]<stdout>:rootdir: /Users/runner/work/horovod/horovod, configfile: setup.cfg
[1]<stdout>:plugins: forked-1.3.0
[0]<stdout>:collecting ... collected 37 items
[0]<stdout>:
[1]<stdout>:collecting ... collected 37 items
[1]<stdout>:
[0]<stderr>:[/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-qh1mu9wy/third_party/gloo/gloo/transport/uv/libuv.h:602] uv_read_start: connection already in progress
[0]<stderr>:Fatal Python error: Aborted
[0]<stderr>:
[0]<stderr>:Thread 0x0000000108e25dc0 (most recent call first):
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/common/basics.py", line 65 in init
[0]<stderr>:  File "/Users/runner/work/horovod/horovod/test/parallel/test_mxnet.py", line 869 in test_allgather_object
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/unittest/case.py", line 628 in run
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/unittest/case.py", line 676 in __call__
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/unittest.py", line 321 in runtest
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 255 in <lambda>
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 311 in from_call
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 255 in call_runtest_hook
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 215 in call_and_report
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 126 in runtestprotocol
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
[0]<stderr>:  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
[1]<stderr>:../../pytest.sh: line 1: 18219 Abort trap: 6           pytest -v --capture=no --continue-on-collection-errors --junit-xml=/Users/runner/work/horovod/horovod/artifacts/test-cpu-gloo-py3_8-tf2_2_0-keras2_3_1-torch1_5_0-mxnet1_5_0-macos/junit.$1.${HOROVOD_RANK:-${OMPI_COMM_WORLD_RANK:-${PMI_RANK}}}.$2.xml ${@:2}
[0]<stdout>:test_mxnet.py::MXTests::test_allgather_object Process 0 exit with status code 134.
[1]<stdout>:test_mxnet.py::MXTests::test_allgather_object Process 1 exit with status code 134.
Traceback (most recent call last):
  File "/Users/runner/.pyenv/versions/3.7.7/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/launch.py", line 770, in run_commandline
    _run(args)
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/launch.py", line 760, in _run
    return _run_static(args)
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/launch.py", line 617, in _run_static
    _launch_job(args, settings, nics, command)
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/launch.py", line 733, in _launch_job
    args.verbose)
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/launch.py", line 706, in run_controller
    gloo_run()
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/launch.py", line 722, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/gloo_run.py", line 284, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/Users/runner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/horovod/runner/gloo_run.py", line 271, in launch_gloo
    .format(name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 134
```

**Comment by EnricoMi** [comment]
@leezu yes, it is persistent. Updating gloo means moving `third_party/gloo` submodule to HEAD? @tgaddair what do you think?

**Comment by EnricoMi** [comment]
@leezu updating gloo fixed it, thanks!

**Comment by EnricoMi** [comment]
@tgaddair: shall be go forward with this? Please especially review the concurrency:
https://github.com/horovod/horovod/blob/8841de4cbf438d7837c794f6c70abd21f9af711f/.github/workflows/ci.yaml#L16-L22
https://github.com/horovod/horovod/blob/8841de4cbf438d7837c794f6c70abd21f9af711f/.github/workflows/ci.yaml#L1434-L1442

The CI workflow includes the Docker workflow, both have concurrency setup. I hope that is the right logic.

**Review by tgaddair — APPROVED** [review]

**Pull request merged**
