### PR TITLE
Correct keras_spark_rossmann_estimator

### PR DESCRIPTION
**Pull request by ConeyLiu**
Expose backend kw args in order to pass extra mpi args to backend. And two small fixes.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
It seems there are other errors in `keras_spark_rossmann_estimator`. I will check it again.

**Comment by ConeyLiu** [comment]
It's ready to review.

**Comment by ConeyLiu** [comment]
When I run the example `keras_spark_rossmann_estimator`. I found there are some warning:
```
WARNING:tensorflow:Entity <function make_petastorm_dataset.<locals>.<lambda> at 0x7f807c0a9950> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: expected exactly one node node, found []
```

And 
```
[1,3]<stderr>:Error in sys.excepthook:
[1,3]<stderr>:
[1,3]<stderr>:Original exception was:
```

Horovod is the master branch and tensorflow is 2.0 version.

**Comment by tgaddair** [comment]
Hey @ConeyLiu, thanks for the PR.

Instead of adding this parameter to the estimator, I'm wondering if it would work for you to use the existing `backend` parameter like this:

```
backend = SparkBackend(num_proc, ...)
estimator = KerasEstimator(backend=backend, ...)
```

I apologize that it isn't documented yet, but the intent is that `num_proc` is just a simplified way of specifying `backend`.

I'll definitely sync with the Petastorm team to figure out what's going on with that warning you mentioned.

**Comment by ConeyLiu** [comment]
very thanks @tgaddair, that works for me. Sorry for not noticing this usage. I have modified the code to just correct the example. Thanks again.

**Comment by ConeyLiu** [comment]
thanks a lot.

**Pull request merged**
