### PR TITLE
Pin tf-nightly

### PR DESCRIPTION
**Pull request by tgaddair**
Latest tf-nightly is failing with the following:

```
Mon Oct 19 12:56:16 2020[1]<stdout>:test_tensorflow2_keras.py:225:
Mon Oct 19 12:56:16 2020[1]<stdout>:_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/_keras/__init__.py:104: in apply_gradients
Mon Oct 19 12:56:16 2020[1]<stdout>:    **kwargs,
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/tensorflow/gradient_aggregation_eager.py:146: in apply_gradients
Mon Oct 19 12:56:16 2020[1]<stdout>:    false_fn=non_aggregation_step,
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201: in wrapper
Mon Oct 19 12:56:16 2020[1]<stdout>:    return target(*args, **kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:1396: in cond_for_tf_v2
Mon Oct 19 12:56:16 2020[1]<stdout>:    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201: in wrapper
Mon Oct 19 12:56:16 2020[1]<stdout>:    return target(*args, **kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:538: in new_func
Mon Oct 19 12:56:16 2020[1]<stdout>:    return func(*args, **kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:1210: in cond
Mon Oct 19 12:56:16 2020[1]<stdout>:    result = false_fn()
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/tensorflow/gradient_aggregation_eager.py:131: in non_aggregation_step
Mon Oct 19 12:56:16 2020[1]<stdout>:    _ = optimizer._aggregate_gradients(transformed_grads_and_vars)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/_keras/__init__.py:83: in _aggregate_gradients
Mon Oct 19 12:56:16 2020[1]<stdout>:    aggregated_grads = self._allreduce(grads)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/_keras/__init__.py:94: in _allreduce
Mon Oct 19 12:56:16 2020[1]<stdout>:    return self._agg_helper.compute_gradients(tuple(grads))
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py:828: in __call__
Mon Oct 19 12:56:16 2020[1]<stdout>:    result = self._call(*args, **kwds)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py:871: in _call
Mon Oct 19 12:56:16 2020[1]<stdout>:    self._initialize(args, kwds, add_initializers_to=initializers)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py:726: in _initialize
Mon Oct 19 12:56:16 2020[1]<stdout>:    *args, **kwds))
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/function.py:2975: in _get_concrete_function_internal_garbage_collected
Mon Oct 19 12:56:16 2020[1]<stdout>:    graph_function, _ = self._maybe_define_function(args, kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/function.py:3367: in _maybe_define_function
Mon Oct 19 12:56:16 2020[1]<stdout>:    graph_function = self._create_graph_function(args, kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/function.py:3212: in _create_graph_function
Mon Oct 19 12:56:16 2020[1]<stdout>:    capture_by_value=self._capture_by_value),
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:990: in func_graph_from_py_func
Mon Oct 19 12:56:16 2020[1]<stdout>:    func_outputs = python_func(*func_args, **func_kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py:634: in wrapped_fn
Mon Oct 19 12:56:16 2020[1]<stdout>:    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/function.py:3893: in bound_method_wrapper
Mon Oct 19 12:56:16 2020[1]<stdout>:    return wrapped_fn(*args, **kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:973: in wrapper
Mon Oct 19 12:56:16 2020[1]<stdout>:    user_requested=True,
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py:454: in converted_call
Mon Oct 19 12:56:16 2020[1]<stdout>:    return _fall_back_unconverted(f, args, kwargs, options, e)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py:501: in _fall_back_unconverted
Mon Oct 19 12:56:16 2020[1]<stdout>:    return _call_unconverted(f, args, kwargs, options)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py:475: in _call_unconverted
Mon Oct 19 12:56:16 2020[1]<stdout>:    return f.__self__.call(args, kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/eager/function.py:3855: in call
Mon Oct 19 12:56:16 2020[1]<stdout>:    return wrapped_fn(self.weakrefself_target__(), *args, **kwargs)
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/horovod-0.20.3-py3.7-macosx-10.15-x86_64.egg/horovod/tensorflow/gradient_aggregation_eager.py:83: in compute_gradients
Mon Oct 19 12:56:16 2020[1]<stdout>:    if tf.equal(self.counter, self.backward_passes_per_step):
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:885: in __bool__
Mon Oct 19 12:56:16 2020[1]<stdout>:    self._disallow_bool_casting()
Mon Oct 19 12:56:16 2020[1]<stdout>:../../env/nightly/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:489: in _disallow_bool_casting
Mon Oct 19 12:56:16 2020[1]<stdout>:    "using a `tf.Tensor` as a Python `bool`")
```

### CODE REVIEW

**Comment by tgaddair** [comment]
CI is currently blocked by https://github.com/NVIDIA/nvidia-docker/issues/1402.

**Review by leezu — APPROVED** [review]

**Comment by tgaddair** [comment]
@aaron276h can you take a look at the failing test?  It's coming from the eager aggregator.  If you install with `tf-nightly`, you should be able to repro.

**Comment by aaron276h** [comment]
@tgaddair Yep will take a look today.

**Comment by aaron276h** [comment]
@tgaddair is there a link to the failed test somewhere in CI or is this something you noticed when running locally?

**Pull request merged**
