### PR TITLE
Fix broken TF DistributedOptimizer with Keras 2.11+

### PR DESCRIPTION
**Pull request by nvcastet**
Signed-off-by: Nicolas Castet <ncastet@nvidia.com>

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [x] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Horovod was only checking for `tf.keras.optimizers.Optimizer` in  `DistributedOptimizer` but supported optimizers are under `tf.keras.optimizers.legacy.Optimizer` for Keras 2.11+.

### CODE REVIEW

**Comment by chongxiaoc** [comment]
There are some tests failing. For example:
```
=================================== FAILURES ===================================
_______________ Tf2KerasTests.test_partial_distributed_optimizer _______________

self = <test_tensorflow2_keras.Tf2KerasTests testMethod=test_partial_distributed_optimizer>

```

**Comment by chongxiaoc** [comment]
But I like this fix. Should land as soon as all tests pass.

**Comment by nvcastet** [comment]
Thanks @chongxiaoc Yes I need to update the different tests/examples. Since with Keras >= 2.11 we were not always using the legacy optimizers.

**Comment by chongxiaoc** [comment]
some missing examples and tests:
```
tensorflow2_mnist_data_service_train_fn_compute_side_dispatcher.py
test/parallel/test_tensorflow2_keras.py
/horovod/examples/tensorflow2/tensorflow2_keras_mnist.py
```

**Comment by pjannaty** [comment]
Thank you both, @chongxiaoc and @nvcastet. This is an important fix for TensorFlow!

**Comment by nvcastet** [comment]
@chongxiaoc Finally, we should be good.

**Review by chongxiaoc — APPROVED** [review]
Thx for fixing it.

**Pull request merged**
