### PR TITLE
Pin GCC to 4.8

### PR DESCRIPTION
**Pull request by alsrgv**
See https://github.com/tensorflow/tensorflow/issues/27067

Updates symlinks to gcc-4.8/g++-4.8 before Horovod installation, and restores them afterward.

NOTE: if Python was built with a more recent version of GCC, it may have incompatible flags in `/usr/lib/python${version}/.../_sysconfigdata*.py`.  We patch the Python installation to remove those flags.

### CODE REVIEW

**Comment by yuxihu** [comment]
Any specific reason that we use Ubuntu in the CI? CentOS 7 comes with gcc 4, which might be an option.

**Comment by alsrgv** [comment]
@yuxihu, I guess just historical reasons - internally we use Debian, and we used to use it until it became too annoying. At that point, we switched to Ubuntu :-)

**Comment by alsrgv** [comment]
GCC 4.8 does not work with pybind11.  This issue seems related: https://github.com/pybind/pybind11/issues/1032

**Comment by alsrgv** [comment]
Superseded by #958

**Pull request closed without merging**
