### PR TITLE
Changes subtitle emphasis 

### PR DESCRIPTION
**Pull request by IgorWilbert**
As mentioned in the comments [here](https://github.com/horovod/horovod/pull/1088), the emphasis of the titles for subsections has to be changed so that they will become links in the `index`.

### CODE REVIEW

**Comment by IgorWilbert** [comment]
@alsrgv I think I got them all. Let me know if you want to include other changes in this PR. BTW, the documentation has changed very fast, good job!

**Comment by alsrgv** [comment]
@IgorWilbert, thanks for the PR!  I agree, docs are getting better and better :-)

Can you try subsections (`~~~`) instead of sections (`---`)?  The sections font feels a bit too big for what used to be subsections before.

**Comment by IgorWilbert** [comment]
Hi @alsrgv ! I did the changes you asked, but it looks identical to me (I'm using Firefox). Also, I think some of the titles could be shorter, like `transport/p2p.cu:431 WARN failed to open CUDA IPC handle : 30 unknown error` seems way too long. What do you think?

**Comment by alsrgv** [comment]
I guess what I wanted to do is not possible with titles: Rather than imposing a fixed number and order of section title adornment styles, the order enforced will be the order as encountered. The first style encountered will be an outermost title (like HTML H1), the second style will be a subtitle, the third will be a subsubtitle, and so on.

Let's keep longer FAQ subtitles - they contain important part of the error, it should make them more discoverable with better search engine matches.

**Pull request merged**
