### PR TITLE
Updated torch c++ to use new aten api

### PR DESCRIPTION
**Pull request by tgaddair**
Related to #3149.

### CODE REVIEW

**Review by chongxiaoc — APPROVED** [review]

**Comment by chongxiaoc** [comment]
torch 1.6.0 as minimum version is because of `LEGACY_CONTIGUOUS_MEMORY_FORMAT`? @tgaddair

**Comment by tgaddair** [comment]
Yes, that's correct.

@EnricoMi do you know why tests are failing due to this error:

```
test_util.py::UtilTests::test_pipe_read_length PASSED
Exception in thread Thread-3:
test_util.py::UtilTests::test_pipe_with_bytes PASSED
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/util/streams.py", line 37, in write
Error:     raise RuntimeError('Pipe is closed')
RuntimeError: Pipe is closed
```

Looks like maybe an issue with the exception being raised on cleanup. Not sure.

**Comment by tgaddair** [comment]
Nevermind, red herring, this is being caused by `test_gen_gpu_heads_pipeline`

**Comment by tgaddair** [comment]
Was able to repro locally on Ubuntu, but only when running the full `test_torch.py` suite. Here's the core dump:

```
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  <signal handler called>
#2  std::string::_Alloc_hider::_Alloc_hider (this=0x7f7190038a60) at /usr/include/c++/9/ext/new_allocator.h:83
#3  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__str=..., this=0x7f7190038a60)
    at /usr/include/c++/9/bits/basic_string.h:3632
#4  horovod::common::TensorTableEntry::TensorTableEntry (this=0x7f7190038a60) at /home/travis/repos/horovod/horovod/common/common.h:344
#5  __gnu_cxx::new_allocator<horovod::common::TensorTableEntry>::construct<horovod::common::TensorTableEntry, horovod::common::TensorTableEntry> (this=0x7f71b464bb90, __p=0x7f7190038a60) at /usr/include/c++/9/ext/new_allocator.h:147
#6  std::allocator_traits<std::allocator<horovod::common::TensorTableEntry> >::construct<horovod::common::TensorTableEntry, horovod::common::TensorTableEntry> (__a=..., __p=0x7f7190038a60) at /usr/include/c++/9/bits/alloc_traits.h:484
#7  std::vector<horovod::common::TensorTableEntry, std::allocator<horovod::common::TensorTableEntry> >::emplace_back<horovod::common::TensorTableEntry> (this=0x7f71b464bb90) at /usr/include/c++/9/bits/vector.tcc:115
#8  std::vector<horovod::common::TensorTableEntry, std::allocator<horovod::common::TensorTableEntry> >::push_back (__x=..., 
    this=0x7f71b464bb90) at /usr/include/c++/9/bits/stl_vector.h:1201
#9  horovod::common::TensorQueue::GetTensorEntriesFromResponse (this=this@entry=0x5645065c7ae0, response=..., 
    entries=std::vector of length 0, capacity 1, joined=false) at /home/travis/repos/horovod/horovod/common/tensor_queue.cc:119
#10 0x00007f7195556af2 in horovod::common::(anonymous namespace)::PerformOperation (process_set=..., response=...)
    at /home/travis/repos/horovod/horovod/common/operations.cc:260
#11 horovod::common::(anonymous namespace)::RunLoopOnce (state=...) at /home/travis/repos/horovod/horovod/common/operations.cc:779
#12 horovod::common::(anonymous namespace)::BackgroundThreadLoop (state=...) at /home/travis/repos/horovod/horovod/common/operations.cc:644
#13 0x00007f71db15c36f in execute_native_thread_routine ()
   from /home/travis/.venv/horovod/nightly/lib/python3.7/site-packages/torch/lib/libc10.so
#14 0x00007f71e3f21609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007f71e3cee293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by tgaddair** [comment]
Segfault occurs with only two tests enabled:

```
[1]<stdout>:test_torch.py::TorchTests::test_horovod_allgather PASSED
[0]<stdout>:test_torch.py::TorchTests::test_horovod_allgather PASSED
[1]<stdout>:test_torch.py::TorchTests::test_horovod_allgather_async_fused PASSED
[0]<stderr>:Fatal Python error: Segmentation fault

```

**Comment by maxhgerlach** [comment]
I looked into the issue with torch nightly a little bit last week. 

With a debug build an assertion in `GetTensorEntriesFromResponse` would be triggered before the segfault is caused via 
```
mpirun -x HOROVOD_LOG_LEVEL=trace -np 2 pytest -sv test/parallel/test_torch.py -k allgather_duplicate_name_error
``` 
But the buggy state is established already a bit earlier. It seems that, when `EnqueueTensorAllgather` encounters a `DUPLICATE_NAME_ERROR` status (as triggered by the test), `ThrowIfError()` does not cause an abort or forward the exception to Python here:
https://github.com/horovod/horovod/blob/181a0aac87cc6a05255244bdce50dac781219759/horovod/torch/mpi_ops_v2.cc#L345

**Comment by tgaddair** [comment]
Going to land these fixes to unblock other PRs. We will continue the investigation into the head failures in a follow-up.

**Pull request merged**
