### PR TITLE
Compile using C++17 when using PyTorch 2.1

### LINKED ISSUE #3996: Horovod 0.28.1 incompatibility with PyTorch 2.1.0
**Environment:**
1. Framework: PyTorch
3. Framework version: 2.1.0
4. Horovod version: 0.28.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes
3. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**

I created the following Dockerfile to test out whether the latest Horovod version (0.28.1) is compatible with the latest PyTorch version (2.1.0):

```
# Use the official Python image as the base image
FROM python:3.10-slim-buster

# Update the system and install necessary libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    ca-certificates \
    libjpeg-dev \
    libpng-dev && \
    rm -rf /var/lib/apt/lists/*

# Install PyTorch
RUN pip install torch==2.1.0

# Install Horovod
RUN HOROVOD_WITH_PYTORCH=1 pip install horovod==0.28.1
```

And it returned various errors that I am unable to decipher. Here is the full build trace: [error.txt](https://github.com/horovod/horovod/files/13168927/error.txt)

### PR DESCRIPTION
**Pull request by thomas-bouvier**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

The minimum required C++ version for compiling PyTorch 2.1 is C++17 (https://github.com/pytorch/pytorch/pull/100557). This commit updates this requirement so that Horovod will also require C++17 if PyTorch >= 2.1.0.

Fixes #3996.

If you validate this change, I'll update the CHANGELOG accordingly.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/GOVERNANCE.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by thomas-bouvier** [comment]
Pinging @maxhgerlach to get some feedback, as I think this PR is quite important.

**Review by jiwq — COMMENTED** [review]
+1  
And should we had plan to use C++17 instead of C++14 as the minimum required C++ standard?

**Comment by wenfeiy-db** [comment]
Hi @thomas-bouvier @jiwq, can we prioritize merging this to fix https://github.com/horovod/horovod/issues/3996?

**Comment by yiliu30** [comment]
Hi @maxhgerlach @EnricoMi  @jiwq ,  #3996 seems to block all users with PT >= 2.1. Some CIs failed due to `No space left on device`, could you please take a look? Thanks

**Comment by EnricoMi** [comment]
Has someone tested this? The installation still fails, though on a different issue:
```
/usr/bin/ld: ../../third_party/compatible_gloo/gloo/libcompatible_gloo.a(store.cc.o):(.rodata+0x0): multiple definition of `gloo::rendezvous::Store::kDefaultTimeout'; CMakeFiles/pytorch.dir/__/common/gloo/http_store.cc.o:(.rodata._ZN4gloo10rendezvous5Store15kDefaultTimeoutE[_ZN4gloo10rendezvous5Store15kDefaultTimeoutE]+0x0): first defined here
```

Tested with
```diff
 # Use the official Python image as the base image
 FROM python:3.10-slim-buster
 
 # Update the system and install necessary libraries
 RUN apt-get update && apt-get install -y \
     build-essential \
     cmake \
     git \
     curl \
     ca-certificates \
     libjpeg-dev \
     libpng-dev && \
     rm -rf /var/lib/apt/lists/*
 
 # Install PyTorch
 RUN pip install torch==2.1.0
 
 # Install Horovod
-RUN HOROVOD_WITH_PYTORCH=1 pip install horovod==0.28.1
+RUN HOROVOD_WITH_PYTORCH=1 pip install git+https://github.com/thomas-bouvier/horovod.git@compile-cpp17
```

**Comment by EnricoMi** [comment]
Looks like we have to build Gloo with C++17 as well: https://github.com/pytorch/pytorch/issues/90448#issuecomment-1342082882

**Comment by EnricoMi** [comment]
Looks like there is some related code in `CMakeLists.txt`:

https://github.com/horovod/horovod/blob/7e4d99386ee4196d767943e30945e45640049ebe/CMakeLists.txt#L377-L393

@maxhgerlach any suggestions?

**Comment by EnricoMi** [comment]
There is some similar logic for tensorflow, which I have mimicked for Pytorch here: https://github.com/horovod/horovod/commit/9f7722ddaec5a1c3d07125827bd7642c23075d7f

**Review by jiwq — COMMENTED** [review]
I like the latest patch. Thanks @EnricoMi catch the important issue.

**Comment by EnricoMi** [comment]
Any suggestions how to debug why `horovod.torch.init()` throws an `std::bad_alloc` when compiled with C++-17 and PyTorch 2.1.x? https://github.com/horovod/horovod/pull/3979#issuecomment-1872594247

**Comment by thomas-bouvier** [comment]
I guess https://github.com/horovod/horovod/pull/3979 needs to be merged to test against PyTorch 2.1. I will have a look at the bad alloc.

**Comment by heliar-k** [comment]
Any progress of this PR?

**Comment by thomas-bouvier** [comment]
Unfortunately, no progress so far. The blocker is a bad allocation `std::bad_alloc`error mentioned by @EnricoMi above. Feel free to investigate https://github.com/horovod/horovod/pull/3979#issuecomment-1900662475 if you have some time.

**Comment by matbun** [comment]
Any news on this PR?

**Comment by EnricoMi** [comment]
Did anyone here see the `bad_alloc` issue with PyTorch 2.1 and this C++17 fix?

https://github.com/horovod/horovod/pull/3979#issuecomment-1891549140

**Comment by matbun** [comment]
> Did anyone here see the `bad_alloc` issue with PyTorch 2.1 and this C++17 fix?
> 
> [#3979 (comment)](https://github.com/horovod/horovod/pull/3979#issuecomment-1891549140)

I have been using this fix for quite some time with no problems: https://github.com/horovod/horovod/issues/3996#issuecomment-2098507345

Is it what you are asking about?

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Pull request merged**
