### PR TITLE
Move ppc64le CI to TF 2.6.0 and PyTorch 1.9.1

### PR DESCRIPTION
**Pull request by nvcastet**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fix ppc64le CI.

Move to ppc64le CI to TF 2.6.0 anf PyTorch 1.9.1. Also using RedHat UBI image (Ubuntu is not supported anymore for ppc64le with the AI stack).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by nvcastet** [comment]
@tgaddair You are good for merging this PR?

**Review by tgaddair — APPROVED** [review]

**Comment by EnricoMi** [comment]
@nvcastet master just moved to pytorch 1.10.0 (df187972). Any chance / need to move ppc64le as well?

**Comment by EnricoMi** [comment]
Looks like we need to move to TF 2.7.0 across all OS as well.

**Comment by nvcastet** [comment]
@EnricoMi We would need to rebuild ppc64le container to https://github.com/open-ce/open-ce/releases/tag/open-ce-v1.5.0.
The ppc64le CI is a safety net to make sure nothing major breaks there, we don't really need to be on the latest.

**Pull request merged**
