### PR TITLE
add allgather cache

### PR DESCRIPTION
**Pull request by Agoniii**
Signed-off-by: Agoniii <815244047@qq.com>

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Add response_cache for Allgather

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by romerojosh** [comment]
Hi @Agoniii, thanks for extending the response cache to cover allgather collectives!

The unit test failure of `test_broadcast_object` does uncover an existing bug in the response cache implementation. The issue is that the checks to see if messages or responses are cached (i.e. the two `ResponseCache::cached` methods) do not check that the `RequestType` and `ResponseType` are the same. Hence, if two Horovod operations are scheduled with the same name, but do different collective operations and the first operation is cached, the execution of the second operation is incorrect. 

In the unit test failure, `test_allgather_object` performs an allgather using the name `dict.sz` and caches it. Then the following `test_broadcast_object` performs a broadcast using the same name `dict.sz`; however, it sees the existing entry in the cache from the allgather, and proceeds to perform the wrong operation. I will push a quick PR to fix this issue to unblock this one.

**Comment by romerojosh** [comment]
Posted #2873 that should fix the issue and resolve these test failures. Will try to get that approved and merged soon to unblock you.

**Comment by Agoniii** [comment]
@romerojosh Thanks. I cherry-picked the #2873 to test whether it can solve these failures.

**Review by romerojosh — APPROVED** [review]
LGTM!

**Pull request merged**
