### PR TITLE
Update usage of TensorFlow Status

### PR DESCRIPTION
**Pull request by ashahba**
## Checklist before submitting

- [X] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)? Y
- [] Did you update the docs? N/A
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users? N/A

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by maxhgerlach** [comment]
Thanks for looking into this. Horovod maintains compatibility with TF 1.15+. I think we could either go with `Status()` or if we feel that's not explicit enough, add a preprocessor branch with updated code for TF 2.10+.

**Review by Tixxx — CHANGES_REQUESTED** [review]
Could you use Status() instead of OkStatus()? Status() is backward compatible.

**Comment by ashahba** [comment]
> Thanks for looking into this. Horovod maintains compatibility with TF 1.15+. I think we could either go with `Status()`, or if we feel that's not explicit enough, add a preprocessor branch with updated code for TF 2.10+.

Thanks Max!
I'm open to ideas.

**Comment by yimeisun123** [comment]
When using horovod with master of Tensorflow, it fails as Status::OK() is no longer supported by Tensorflow master.

**Comment by ashahba** [comment]
I'll go with `Status()`

**Review by Tixxx — APPROVED** [review]

**Comment by Tixxx** [comment]
will merge after CI passes

**Pull request merged**
