### PR TITLE
Bump version to 0.28.0

### PR DESCRIPTION
**Pull request by maxhgerlach**
Preparing release v0.28.0.

I aimed to add all user-facing changes to the changelog, roughly in commit order. Please have a look if everything looks right.

### CODE REVIEW

**Review by nvcastet — APPROVED** [review]
Thank you Max.!

**Review by EnricoMi — APPROVED** [review]
LGTM! Nice work!

**Review by Tixxx — APPROVED** [review]

**Review by shawnccx — APPROVED** [review]

**Review by chongxiaoc — APPROVED** [review]

**Comment by maxhgerlach** [comment]
CI builds fail, apparently because of https://github.com/docker/docker-py/issues/3113

Let's also see if we can get #3912 in.

**Comment by EnricoMi** [comment]
A usual, these things break when doing a release...

**Pull request merged**
