### PR TITLE
Migrate to the new oneCCL API

### PR DESCRIPTION
**Pull request by shirosankaku**
## Checklist before submitting

- [yes] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [no need] Did you update the docs?
- [no need] Did you write any tests to validate this change?  
- [yes] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

Fixing the issue [#2499](https://github.com/horovod/horovod/issues/2499)

## Description
Updated oneCCL related files with oneCCL new API. No need to update docs and write extra tests.

oneCCL v1.0 specification
https://oneapi-src.github.io/oneAPI-spec/elements/oneCCL/source/index.html

### CODE REVIEW

**Comment by fschlimb** [comment]
Thanks @shirosankaku !

**Comment by shirosankaku** [comment]
@tgaddair Could you, please, review?

**Comment by shirosankaku** [comment]
@tgaddair , The PR is ready to be merged

**Review by tgaddair — APPROVED** [review]
Thanks @shirosankaku @fschlimb!

**Pull request merged**
