### PR TITLE
Upgrade GHA versions, fix publish-test-results warning

### PR DESCRIPTION
**Pull request by EnricoMi**
Upgrades GHA in CI to latest major versions.

### CODE REVIEW

**Comment by maxhgerlach** [comment]
@EnricoMi, the entire `build-and-test` matrix seems to have been skipped in the CI run: https://github.com/horovod/horovod/actions/runs/3492163284

**Comment by maxhgerlach** [comment]
https://github.com/horovod/horovod/actions/runs/3492163284/jobs/5845635522

> No code changes, no need to build and test

Should we maybe commit some no-op code change to trigger the entire pipeline?

**Comment by EnricoMi** [comment]
> Should we maybe commit some no-op code change to trigger the entire pipeline?

What about testing in PROD? :laughing:

**Review by maxhgerlach — APPROVED** [review]
Looks great!

**Comment by maxhgerlach** [comment]
CodeQL / Analyze {Python,C++} were canceled now, but passed before https://github.com/horovod/horovod/actions/runs/3492163297

**Pull request merged**
