### PR TITLE
Bump build partially to C++17 for TensorFlow 2.10+

### LINKED ISSUE #3566: Unit test "test_spark_keras" fails with TF head:
```
self = <test_spark_keras.SparkKerasTests testMethod=test_fit_model>

    def test_fit_model(self):
        model = create_xor_model()
        optimizer = tf.keras.optimizers.SGD(lr=0.1)
        loss = 'binary_crossentropy'
    
        with spark_session('test_fit_model') as spark:
            df = create_xor_data(spark)
    
            with local_store() as store:
                keras_estimator = hvd.KerasEstimator(
                    num_proc=2,
                    store=store,
                    model=model,
                    optimizer=optimizer,
                    loss=loss,
                    feature_cols=['features'],
                    label_cols=['y'],
                    batch_size=1,
                    random_seed=1,
                    epochs=3,
                    verbose=2,
                    use_gpu=False)
    
                assert not keras_estimator.getUseGpu()
    
>               keras_model = keras_estimator.fit(df)

test_spark_keras.py:106: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/dist-packages/horovod/spark/common/estimator.py:35: in fit
    return super(HorovodEstimator, self).fit(df, params)
/usr/local/lib/python3.8/dist-packages/pyspark/ml/base.py:161: in fit
    return self._fit(dataset)
/usr/local/lib/python3.8/dist-packages/horovod/spark/common/estimator.py:80: in _fit
    return self._fit_on_prepared_data(
/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/estimator.py:270: in _fit_on_prepared_data
    serialized_model = self._compile_model(keras_utils)
/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/estimator.py:318: in _compile_model
    dist_optimizer = keras_utils.get_horovod().DistributedOptimizer(**dist_optimizer_args)
/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/util.py:99: in get_horovod
    return TFKerasUtil.horovod_fn()()
/usr/local/lib/python3.8/dist-packages/horovod/spark/keras/util.py:104: in fn
    import horovod.tensorflow.keras as hvd
/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/__init__.py:26: in <module>
    from horovod.tensorflow import elastic
/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/elastic.py:24: in <module>
    from horovod.tensorflow.functions import broadcast_object, broadcast_object_fn, broadcast_variables
/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/functions.py:24: in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, broadcast_
/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_ops.py:53: in <module>
    raise e
/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_ops.py:50: in <module>
    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_ops.py:45: in _load_library
    library = load_library.load_op_library(filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

library_filename = '/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_lib.cpython-38-x86_64-linux-gnu.so'

    @tf_export('load_op_library')
    def load_op_library(library_filename):
      """Loads a TensorFlow plugin, containing custom ops and kernels.
    
      Pass "library_filename" to a platform-specific mechanism for dynamically
      loading a library. The rules for determining the exact location of the
      library are platform-specific and are not documented here. When the
      library is loaded, ops and kernels registered in the library via the
      `REGISTER_*` macros are made available in the TensorFlow process. Note
      that ops with the same name as an existing op are rejected and not
      registered with the process.
    
      Args:
        library_filename: Path to the plugin.
          Relative or absolute filesystem path to a dynamic library file.
    
      Returns:
        A python module containing the Python wrappers for Ops defined in
        the plugin.
    
      Raises:
        RuntimeError: when unable to load the library or get the python wrappers.
      """
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
E     tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_lib.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl12lts_2021110211string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS9_EE

/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py:54: NotFoundError
```

### PR DESCRIPTION
**Pull request by othakkar**
TF nightly builds are currently failing due to requiring C++17 support. Hence, this PR updates it to C++17.

Fixes #3566.

### CODE REVIEW

**Comment by maxhgerlach** [comment]
Hi @othakkar,

what are the symptoms of failures with TF nightly due to building in C++14 mode rather than C++17? We are getting missing symbol errors on import like 
```
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
E     tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_lib.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl12lts_2021110211string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS9_EE
```
Are those related?

Anyway, I kicked off the CI workflows, but this will probably take some tweaking until Horovod builds fine in all configurations.

**Comment by maxhgerlach** [comment]
(Some of) those non-TF-head build failures reported for the CI jobs should be fixed via #3555.

**Comment by maxhgerlach** [comment]
Thanks for rebasing, @othakkar!

Some of the builds with earlier versions of TF now fail with similarly sounding import errors, e.g.:
```
[0]<stdout>:E   tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_lib.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceESt17basic_string_viewIcSt11char_traitsIcEEPSt6vectorISsSaISsEE
```
on https://github.com/horovod/horovod/runs/6703462264?check_suite_focus=true

Presumably we will have to build with C++17 only when working with TensorFlow post 2.9.x, and otherwise stick with C++14?

Others fail because of something related to GitHub Actions setup. Have you seen this before, @EnricoMi?
```
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
Download action repository 'actions/setup-python@v2' (SHA:7f80679172b057fc5e90d70d197929d454754a5a)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_a74df43c-2f83-45a6-bf47-d2c1af3ce01a/c1b38827-8616-48e1-adb7-4078c75a1176.tar.gz. return code: 2.
```
on https://github.com/horovod/horovod/runs/6703462098?check_suite_focus=true

**Comment by EnricoMi** [comment]
@othakkar you can rebase to this branch: https://github.com/horovod/horovod/pull/3557

This adds TF 2.9.1 to the CI.

**Comment by othakkar** [comment]
@maxhgerlach @EnricoMi looks like there are still some undefined symbol errors. Let me know if I can do something to help!

**Comment by maxhgerlach** [comment]
> Looks like we need to control from the outside when to build with C++17 or C++14. @othakkar @maxhgerlach can you add this to CMake?

Hmm, I would hope that it will be sufficient to enable C++17 only for source files in `horovod/tensorflow` and that this could be triggered without looking at an environment variable, just by parsing the version number of TensorFlow. We don't include any tensorflow headers anywhere else, so presumably there shouldn't be any other symbol mismatches then. 

I can give this a try, but not before Tuesday next week.

**Comment by nvcastet** [comment]
@maxhgerlach @EnricoMi @othakkar Ok I pushed a commit to this PR that should fix the issue:
* If TF >= 2.10 use std=c++17 for horovod cpp extension and also for gloo dependency (otherwise `multiple definition` linking error because `constexpr` behavior changed slightly between c++14 and c++17)

**Comment by EnricoMi** [comment]
@nvcastet I thought this is since 2.9. Then I am seeing some other issue with 2.9.1: https://buildkite.com/horovod/horovod/builds/7804#01811fe6-387d-4ce5-821a-4deaaecc8697

@othakkar please rebase back to master.

**Comment by nvcastet** [comment]
@EnricoMi What is the error you are getting for TF 2.9?
I think it is since https://github.com/tensorflow/tensorflow/commit/8ea5ed0c392b329a3e0481a3f1f7b0ca86821b84 which is in the master branch and not the `2.9` one.

**Comment by EnricoMi** [comment]
@nvcastet let's discuss that in #3557.

**Comment by othakkar** [comment]
> @nvcastet I thought this is since 2.9. Then I am seeing some other issue with 2.9.1: https://buildkite.com/horovod/horovod/builds/7804#01811fe6-387d-4ce5-821a-4deaaecc8697
> 
> @othakkar please rebase back to master so that commits [82e738f](https://github.com/horovod/horovod/commit/82e738fa772bc695ff6da7428e238271ad6f084d) and [cf7653c](https://github.com/horovod/horovod/commit/cf7653ca9e3e861d798222e6378e9496a85f4545) get removed from this branch again.

@EnricoMi Since I already have the two commits on my remote branch, I am not sure how to remove them without reverting the two commits. I tried to move to a previous commit and cherry-pick [858f6a6](https://github.com/horovod/horovod/pull/3558/commits/858f6a6ed6170e2f2ccc3b27aa3cc4aa463e5412) and [a432456](https://github.com/horovod/horovod/pull/3558/commits/a4324567028ce3e57879949c62320a738960873f) but somehow it did not work. I can either revert the two commits or create a new PR. Please advise!

**Comment by maxhgerlach** [comment]
@nvcastet, thanks for taking the time to work out the CMake!

----

@othakkar, after making sure that your local master is up to date, I would suggest to
```
$ git rebase --interactive master
```
on your local `c++17` branch, then (in your editor that has just opened) tell `git` to drop the unwanted commits and only keep the two c++17 / tf 2.10 commits. That should go through easily because there are no conflicts. I believe that you should be able to force-push that branch to the existing PR on GitHub then.

**Comment by maxhgerlach** [comment]
Import errors with `tfhead` appear to be mitigated, however tests in the CI now run into the 10 minute timeout: https://github.com/horovod/horovod/runs/6770140747?check_suite_focus=true 

It's on CPU and pytest only spends ~72 seconds on `test_tensorflow.py` if I read the logs correctly:
```
[0]<stdout>:------ generated xml file: /artifacts/junit.gloo.0.test_tensorflow.py.xml ------
[0]<stdout>:============ 80 passed, 44 skipped, 22 warnings in 72.62s (0:01:12) ============
```
So I assume it's not the issue described in #3557, but maybe something with `torchhead`? In 3/3 attempts the jobs is aborted after `TorchTests::test_horovod_join_allgather`.

**Comment by othakkar** [comment]
> @nvcastet, thanks for taking the time to work out the CMake!
> 
> @othakkar, after making sure that your local master is up to date, I would suggest to
> 
> ```
> $ git rebase --interactive master
> ```
> 
> on your local `c++17` branch, then (in your editor that has just opened) tell `git` to drop the unwanted commits and only keep the two c++17 / tf 2.10 commits. That should go through easily because there are no conflicts. I believe that you should be able to force-push that branch to the existing PR on GitHub then. (If that still doesn't work for some reason, reverting the two commits and leaving them on the branch would be OK as well. When all is done, we will squash-merge anyway, so there won't be any commit noise on master.)

Thanks @maxhgerlach. I just rebased and pushed using your suggestion!

**Comment by EnricoMi** [comment]
Eight parallel tests disappeared:
```
test.parallel.test_adasum_tensorflow
test.parallel.test_keras
test.parallel.test_process_sets_multi_comm
test.parallel.test_process_sets_static
test.parallel.test_tensorflow
test.parallel.test_tensorflow2_keras
test.parallel.test_tensorflow_keras
test.parallel.test_xla
```
Why haven't they been executed by the CI?

**Comment by EnricoMi** [comment]
Looks like these 8 "tests" have been introduced when TF head started to fail, and now that this is fixed, the disappear. Looking closely, they are not tests but test files.

Last time master build succeeded: 768 tests (https://github.com/horovod/horovod/runs/6501610281)
First time master build failed on TF head: 776 tests (https://github.com/horovod/horovod/runs/6699633859)

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
@maxhgerlach happy?

**Review by maxhgerlach — APPROVED** [review]
LGTM! 

I edited the title a bit.

**Comment by EnricoMi** [comment]
Do we need to amend the documentation (where it mentions CMake dependency) and CHANGELOG.md?

**Comment by maxhgerlach** [comment]
> Do we need to amend the documentation (where it mentions CMake dependency) and CHANGELOG.md?
> 
> We can do that in a follow up PR to avoid full CI cycles for these changes.

Good point! And I agree that it would be wise to do this in a separate PR.

CMake supports C++17 from version 3.8, so hopefully we should be good there with 3.13+. https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html

We could add a phrase then like: "To install Horovod with TensorFlow 2.10 or later you will need a compiler that supports C++17 like `g++8` or newer."

`gcc` seems to support all features of C++17 starting with version 8. https://gcc.gnu.org/projects/cxx-status.html#cxx17

**Pull request merged**
