### PR TITLE
test: pin pytorch-lighting to 1.4.1

### PR DESCRIPTION
**Pull request by chongxiaoc**
Signed-off-by: Chongxiao Cao <chongxiaoc@uber.com>

## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by chongxiaoc** [comment]
@irasit 
Actually this PR didn't touch `torch==1.3.1+cu100` and `pytorch_lightning==1.1.0` part.

All other versions of pytorch are >= `1.6.0` and should be well supported by `pytorch_lightning==1.4.1`.
See pytorch lightning github CI dockerfile setup for `1.4.1` here: https://github.com/PyTorchLightning/pytorch-lightning/blob/1.4.1/dockers/base-conda/Dockerfile#L17

And lightning-related unit tests are all enabled and passed here: https://github.com/horovod/horovod/pull/3116/checks?check_run_id=3356547567

Please take a look, thanks!

**Comment by chongxiaoc** [comment]
@EnricoMi Can you take a look as well? I think it is good to go now.

**Comment by chongxiaoc** [comment]
moved to https://github.com/horovod/horovod/pull/3117 for torch==1.4.0 compatibility.

**Comment by EnricoMi** [comment]
@chongxiaoc did you find out why 1.4.1 does not work?

**Comment by chongxiaoc** [comment]
> @chongxiaoc did you find out why 1.4.1 does not work?

Lightning `1.4.1` doesn't support torch 1.4.0

```
pytorch-lightning 1.4.1 requires torch>=1.6, but you have torch 1.5.0 which is incompatible.
```

I think PL 1.3.8 should work based on their CI docker file: https://github.com/PyTorchLightning/pytorch-lightning/blob/1.3.8/dockers/base-conda/Dockerfile#L19
And I just tested locally it works.

**Pull request closed without merging**
