### PR TITLE
Fix broken Dockerfile due to change in oneCCL deps paths

### PR DESCRIPTION
**Pull request by francares**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

When trying to build a Docker image using oneCCL as dependency, it fails due to a path change in latest master oneCCL repository (https://github.com/oneapi-src/oneCCL).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by EnricoMi** [comment]
Thanks for fixing this. Why is the oneccl installation doing all this copying anyway? Their README states, installation is as simple as

    mkdir build
    cd build
    cmake ..
    make -j install

https://github.com/oneapi-src/oneCCL#installation

**Comment by EnricoMi** [comment]
It even has CMake integration: https://github.com/oneapi-src/oneCCL#using-oneccl-package-from-cmake

**Comment by francares** [comment]
> Thanks for fixing this. Why is the oneccl installation doing all this copying anyway? Their README states, installation is as simple as
> 
> ```
> mkdir build
> cd build
> cmake ..
> make -j install
> ```
> 
> https://github.com/oneapi-src/oneCCL#installation

@EnricoMi, these steps are already there (https://github.com/horovod/horovod/blob/4b8cc49826e21abc84112e43e90b46258a7af528/Dockerfile.test.cpu#L104) but you are right, the steps related to copying dependencies are not needed. I'm going to remove those steps from the Docker file.
I'm also going to add a new step to remove `oneccl.tar.gz` and the tmp build folder `/tmp/oneCCL-${CCL_PACKAGE}/` after install.
OTH, I'm seeing the oneCCL [build](<https://github.com/horovod/horovod/runs/5688852371?check_suite_focus=true>) is stuck. I can't see the details on why. Can you take a look to it?

**Comment by EnricoMi** [comment]
That is the strange bit: GitHub CI cannot build that image, it gets stuck. Looks like the VM itself dies: https://github.com/horovod/horovod/issues/2846

**Comment by francares** [comment]
@EnricoMi Good catch on the cmake flag. Thanks for fixing it. I'm seeing now that some tests from `MPI_Cluster_PyTests_ONECCL_MPI` and `MPI_Cluster_PyTests_ONECCL_OFI` are failing with an unexpected error code 255 (expected error code is 1). It might be due to `HOROVOD_CPU_OPERATIONS=CCL` is not set. I'm working on it.

**Comment by EnricoMi** [comment]
Good point, could be part of #2846.

**Pull request merged**
