### PR TITLE
pin pytorch_lighting to 1.3.8

### PR DESCRIPTION
**Pull request by chongxiaoc**
Fix compatibility for torch==1.4.0

Signed-off-by: Chongxiao Cao <chongxiaoc@uber.com>

## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by EnricoMi** [comment]
@chongxiaoc sorry, this still fails on GPU: https://buildkite.com/horovod/horovod/builds/6387

**Comment by chongxiaoc** [comment]
ok, that's logging function issue.
Let me create a ticket to track.

**Comment by chongxiaoc** [comment]
here: https://github.com/horovod/horovod/issues/3119

**Pull request merged**
