### PR TITLE
Add executable arg to horovod.spark.run

### PR DESCRIPTION
**Pull request by darkjh**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Add parameter to specify an executable path for workers spawn by horovod on spark.
Useful in situations where the python env is shipped with `conda-pack` or https://github.com/criteo/cluster-pack
PR similar to #2708 

Tested with horovod on spark in a CPU cluster.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by darkjh** [comment]
Fixed commit signoff

**Comment by tgaddair** [comment]
Hey @darkjh, thanks for the PR! Could you rebase this change from master? The most recent changes should fix the failing unit test.

**Review by EnricoMi — APPROVED** [review]
LGTM!

**Comment by darkjh** [comment]
@EnricoMi Thanks for the review!
@tgaddair rebased, seems the test errors not related to the changes, anything to worry about?

**Comment by EnricoMi** [comment]
The reported failed tests are all tests that have been retried and eventually succeeded (flaky tests). So I would say nothing for you @darkjh  to worry about but something to look after by the Horovod team @tgaddair.

**Pull request merged**
