### PR TITLE
Move torch-nightly to cu118 from cu116

### PR DESCRIPTION
**Pull request by maxhgerlach**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

https://github.com/horovod/horovod/pull/3864#issuecomment-1472544769:

> After yesterday's PyTorch release we pick up `torch==2.0.0` now, rather than a nightly/dev version, which blocks the CI:
> 
> ```
> 2023-03-16T17:52:42.3497842Z #44 [39/51] RUN /horovod/assert-package-versions.sh
> 2023-03-16T17:52:42.3498192Z #44 sha256:94c0c4138de63c79ca985f9905edc3b9f598aa742087af4998fd87a12805d32f
> 2023-03-16T17:52:43.1000727Z #44 0.739 tf-nightly==2.13.0.dev20230316 [32mfound[0m (matches tf-nightly / tf-nightly==.*\.dev20\d{6})
> 2023-03-16T17:52:44.0024362Z #44 1.680 torch==2.0.0 [31mfound BUT[0m torch-nightly-cu116 / torch==.*\.dev20\d{6}.* [31mexpected[0m
> 2023-03-16T17:52:44.4534918Z #44 2.151 pytorch-lightning==1.5.9 [32mfound[0m
> 2023-03-16T17:52:45.3372508Z #44 3.095 torchvision==0.15.1 [31mfound BUT[0m torchvision / torchvision==.*\.dev20\d{6}.* [31mexpected[0m
> 2023-03-16T17:52:45.9391226Z #44 3.572 mxnet-cu112==2.0.0b20230316 [32mfound[0m (matches mxnet-nightly-cu112 / mxnet-cu112==.*20\d{6})
> 2023-03-16T17:52:46.3132460Z #44 4.041 pyspark==3.3.1 [32mfound[0m
> 2023-03-16T17:52:46.3133493Z #44 ERROR: executor failed running [/bin/bash -euo pipefail -c /horovod/assert-package-versions.sh]: exit code: 1
> ```
> 
> I can only find earlier `torch-2.0.0.dev*` packages on: https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html 
> 
> Probably they stopped building for CUDA 11.6. There are newer packages `torch-2.1.0.dev*` on https://download.pytorch.org/whl/nightly/cu118/torch_nightly.html, so upgrading to CUDA 11.8 would be one way to go forward here.
> 

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/GOVERNANCE.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by maxhgerlach** [comment]
`torchhead` appears to build fine for GPU now. Remaining build errors are for `tfhead`, to be dealt with in #3864.

**Comment by EnricoMi** [comment]
Does this also fix the

    torchvision==0.15.1 found BUT torchvision / torchvision==.*\.dev20\d{6}.* expected

**Comment by maxhgerlach** [comment]
> Should NCCL_VERSION_OVERRIDE also be moved to CUDA 11.8?

Probably, but tests won't run until TF builds.

> Does this also fix the
> torchvision==0.15.1 found BUT torchvision / torchvision==.*\.dev20\d{6}.* expected

I would expect that, but the docker build aborts before the checks are run because TF doesn't build yet.

**Comment by maxhgerlach** [comment]
My suggestion would be to merge this small change, then continue at https://github.com/horovod/horovod/pull/3864 until TF builds.

**Pull request merged**
