### PR TITLE
Reactivate oneccl image in CI

### LINKED ISSUE #2846: Make Horovod build with OneCCL in GitHub CI
Moving the CI to GitHub Workflow, Horovod does not build with OnceCCL anymore. This has to be investigated and resolved here.

### PR DESCRIPTION
**Pull request by EnricoMi**
This adds the oneccl image back to the CI. Fixes #2846.

### CODE REVIEW

**Comment by EnricoMi** [comment]
Horovod starts building but then gets stuck at some point. GitHub actions does not timeout and fails to provide log. This is from the live log when the action was running:

```
  ...
  #27 7.231 -- The C compiler identification is GNU 9.4.0
  #27 7.303 -- The CXX compiler identification is GNU 9.4.0
  #27 7.311 -- Check for working C compiler: /usr/bin/cc
  #27 7.386 -- Check for working C compiler: /usr/bin/cc -- works
  #27 7.388 -- Detecting C compiler ABI info
  #27 7.461 -- Detecting C compiler ABI info - done
  #27 7.477 -- Detecting C compile features
  #27 7.478 -- Detecting C compile features - done
  #27 7.482 -- Check for working CXX compiler: /usr/bin/c++
  #27 7.568 -- Check for working CXX compiler: /usr/bin/c++ -- works
  #27 7.569 -- Detecting CXX compiler ABI info
  #27 7.658 -- Detecting CXX compiler ABI info - done
  #27 7.675 -- Detecting CXX compile features
  #27 7.676 -- Detecting CXX compile features - done
  #27 20.57 [ 65%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_app_api_datatype_attr.cpp.o
  #27 20.68 [ 65%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_app_api_init_attr.cpp.o
  #27 20.88 [ 66%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_app_api_kvs_attr.cpp.o
  #27 20.97 [ 66%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_communicator.cpp.o
  #27 21.11 [ 67%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_context.cpp.o
  #27 21.26 [ 67%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_device.cpp.o
  #27 21.43 [ 68%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_environment.cpp.o
  #27 22.30 [ 69%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_stream.cpp.o
  #27 22.38 [ 69%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_kvs.cpp.o
  #27 22.56 [ 69%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_cpp_utils.cpp.o
  #27 22.68 [ 70%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_attr.cpp.o
  #27 22.74 [ 71%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_coll_attr.cpp.o
  #27 22.98 [ 72%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_comm_split_attr.cpp.o
  #27 23.00 [ 72%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_init_attr.cpp.o
  #27 23.02 [ 72%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_comm_attr.cpp.o
  #27 23.42 [ 73%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_kvs_attr.cpp.o
  #27 24.09 [ 73%] Building CXX object src/CMakeFiles/ccl-objects.dir/ccl_empty_stream.cpp.o
```

**Comment by EnricoMi** [comment]
Fixed in #3492.

**Comment by ashiqimranintel** [comment]
Any update on this issue?

**Comment by EnricoMi** [comment]
This is waiting on #2846.

**Comment by maxhgerlach** [comment]
@EnricoMi, I've reopened this PR and rebased it to master following @i-kosarev's comment on the associated issue: https://github.com/horovod/horovod/issues/2846#issuecomment-1521689481 

Hopefully, the unit test failures that were seen before should now be fixed via https://github.com/horovod/horovod/pull/3895.

**Comment by i-kosarev** [comment]
I think there are some version updates needed. I will be able to assist later

**Comment by maxhgerlach** [comment]
A couple of the test in `MPI Parallel PyTests [ONECCL OFI]` fail, in particular those related to `min`, `max`, `product` allreduce ops: 
https://github.com/horovod/horovod/runs/13939072400 (These are relatively recent additions to Horovod.) No failures for `MPI Parallel PyTests [ONECCL MPI]`.

**Comment by i-kosarev** [comment]
Thanks! Didn't realize the issues are only related to ONECCL OFI. Anyway, I think we might have some related fixes in the latest oneCCL versions, so version updates might help

**Comment by maxhgerlach** [comment]
Thanks! Please advise what should be updated. 🙂 

Currently `CCL_PACKAGE` is set to `master`:
https://github.com/horovod/horovod/blob/master/Dockerfile.test.cpu#L22 It would be best to pin a recent version.

**Pull request closed without merging**
